# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-License-Identifier: CC0-1.0
#
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Python packages
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs

  # Maintain dependencies inside uv lock file
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs

  # Maintain dependencies for GitHub actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs

  # Maintain dependencies for pre-commit config
  - package-ecosystem: pre-commit
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 0  # prevents normal PRs, allows security PRs
