# SPDX-FileCopyrightText: 2026 German Aerospace Center (DLR)
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "fl-demonstrator"
SPDX-PackageSupplier = ["2026 German Aerospace Center (DLR)"]
SPDX-PackageDownloadLocation = "https://github.com/DLR-KI/fl-demonstrator"

[[annotations]]
path = ["uv.lock"]
precedence = "aggregate"
SPDX-FileCopyrightText = ["2026 German Aerospace Center (DLR)"]
SPDX-License-Identifier = "Apache-2.0"
