@startuml Models
!theme plain

object NotificationReceiver {
  id: UUID
  message_endpoint: URL
}
object User {
  username: Varchar(150)
  first_name: Varchar(150)
  last_name: Varchar(150)
  email: Email
  actor: Boolean
  client: Boolean
}
object Token {
  key: Varchar(40)
  created: DateTime
}
object Model {
  id: UUID
  round: Int
  weights: Binary
}
object GlobalModel {
  name: Varchar(256)
  description: Text
}
object SWAGModel {
  swag_first_moment: Binary
  swag_second_moment: Binary
}
object MeanModel
object LocalModel {
  sample_size: Int
}
object Training {
  id: UUID
  state: TrainingState
  target_num_updates: Int
  last_update: DateTime
  aggregation_method: AggregationMethod
  uncertainty_method: UncertaintyMethod
  options: JSON
  locked: Boolean
}
object Metric {
  identifier: Varchar(64)
  key: Varchar(32)
  value: Float | Blob
  step: Int
}

' ===================================
Model "1..*" -up-> "1" User : owner
Model "1" <-left- "*" Metric : model
GlobalModel --|> Model
SWAGModel -up-|> GlobalModel
MeanModel --|> GlobalModel
MeanModel -[hidden]left-> GlobalModel : "\t"
MeanModel "*" --> "1..*" GlobalModel
LocalModel -up-|> Model
LocalModel "1..*" -right-> "1" GlobalModel : base_model
Training "1" --> "1" GlobalModel : model
Training -[hidden]right-> User
Training "1..*" --> "1..*" User : participants
Training "1..*" --> "1" User : actor
Token "1" --> "1" User : user
User -right-|> NotificationReceiver
Metric "1..*" -up-> "1" User : reporter
@enduml