@startuml Model Enums
!theme plain
hide enum methods

enum TrainingState {
  I
  O
  C
  E
  S
}
enum AggregationMethod {
  FedAvg
  FedDC
  FedProx
}
enum UncertaintyMethod {
  NONE
  ENSEMBLE_LOCAL
  ENSEMBLE_GLOBAL
  MC_DROPOUT
  SWAG
}
@enduml