@startuml Training Process
!theme plain
'skinparam responseMessageBelowArrow true
skinparam style strictuml
skinparam sequence {
  LifeLineBorderColor #848484
  GroupBorderColor #848484
}

Actor Actor
participant WebServer
database Database
collections Clients
participant "Celery Task Queue" as celery

activate Actor

Actor -> WebServer ++ : Create Model
WebServer -> Database ++ : Store Model
Database -->> WebServer --
WebServer -->> Actor --

Actor -> WebServer ++ : Create Training
WebServer -> Database ++ : Store Training
Database -->> WebServer --
WebServer -->> Actor --

Actor ->> WebServer --++ : Start Training
WebServer ->> Clients ++ : Start Training
deactivate Clients

loop For n Updates
  WebServer ->> Clients --++ : Start Training Round

  WebServer <- Clients ++ : Download Global Model
  WebServer --> Clients -- : Global Model

  Clients -> Clients ++ : Train Local Model
  Clients -[hidden]-> Clients --

  Clients ->> WebServer --++ : Upload Local Model
  WebServer -> Database ++ : Store Local Model
  Database -->> WebServer --

  note over WebServer,celery #eeeeee
    continue if **all** __//model uploads//__ arrived
  end note

  WebServer ->> celery --++ : Dispatch Aggregation Task

  celery -> Database ++ : Get Local Models
  Database --> celery --

  celery -> celery ++ : Do Aggregation
  celery -[hidden]-> celery --

  celery -> Database ++ : Store "New" Global Model
  Database --> celery --

  celery -> Database ++ : Clean Up Local Models
  Database --> celery --

  celery ->> Clients --++ : Start Model Test

  WebServer <- Clients ++ : Download Global Model
  WebServer --> Clients -- : Global Model

  Clients -> Clients ++ : Test Global Model
  Clients -[hidden]-> Clients --

  Clients ->> WebServer --++ : Upload Global Model Test Metrics
  WebServer -> Database ++ : Store Test Metrics
  Database -->> WebServer --

  note over WebServer,celery #eeeeee
    continue if **all** __//test metrics//__ arrived
  end note
end

WebServer ->> Clients ++ : Training Finished
WebServer ->> Actor --++: Training Finished
deactivate Clients
deactivate Actor
@enduml