---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-django
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP

  selector:
    app: {{ .Values.name }}