# Generated by Django 4.0.10 on 2023-07-18 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalmodel',
            name='swag_first_moment',
        ),
        migrations.RemoveField(
            model_name='globalmodel',
            name='swag_second_moment',
        ),
        migrations.CreateModel(
            name='SWAGModel',
            fields=[
                ('globalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fl_server_core.globalmodel')),
                ('swag_first_moment', models.BinaryField()),
                ('swag_second_moment', models.BinaryField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fl_server_core.globalmodel',),
        ),
        migrations.CreateModel(
            name='MeanModel',
            fields=[
                ('globalmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fl_server_core.globalmodel')),
                ('models', models.ManyToManyField(related_name='mean_models', to='fl_server_core.globalmodel')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fl_server_core.globalmodel',),
        ),
    ]
