# Generated by Django 4.0.10 on 2023-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0004_training_uncertainty_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='aggregation_method',
            field=models.CharField(choices=[('FedAvg', 'FedAvg'), ('FedDC', 'FedDC'), ('FedProx', 'FedProx')], default='FedAvg', max_length=32),
        ),
        migrations.AlterField(
            model_name='training',
            name='uncertainty_method',
            field=models.CharField(choices=[('NONE', 'None'), ('ENSEMBLE', 'Ensemble'), ('MC_DROPOUT', 'MC Dropout'), ('SWAG', 'SWAG')], default='NONE', max_length=32),
        ),
    ]
