# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 4.0.10 on 2023-09-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0005_alter_training_aggregation_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='uncertainty_options',
            new_name='options',
        ),
    ]
