# Generated by Django 4.0.10 on 2024-02-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0006_rename_uncertainty_options_training_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmodel',
            name='input_shape',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
