# Generated by Django 4.0.10 on 2024-02-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0007_globalmodel_input_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmodel',
            name='input_shape',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
