# Generated by Django 6.0.6 on 2026-06-17 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fl_server_core', '0008_globalmodel_preprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edc',
            fields=[
                ('bpn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
