apiVersion: v2
name: dlr-fl-demonstrator-django
type: application
appVersion: "0.0.1"
version: 0.0.1

dependencies:
  - name: postgresql
    version: "14.3.3"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
